### ISSUE TITLE
privateKey option ignored

### ISSUE THREAD

**Issue by tchap** [oncletom/grunt-crx#50]
When I set `privateKey` in the `options` object, it is somehow ignored. Things start working when I move it to the top level config. So, example:

DOES NOT work:

```javascript
crx: {
  prod: {
    options:
      privateKey: "..."
  }
}
```

DOES work:

```javascript
crx: {
  prod: {
    privateKey: "..."
  }
}
```

**Comment by oncletom** [comment]
Yep, the online doc is about `v1.x.x` whereas the default installed package is `v0.3.x` (cf. #45).

**Comment by tchap** [comment]
Right... Shouldn't `master` represent what is on NPM?

**Comment by oncletom** [comment]
Indeed but not because of #44, eventually fixed by oncletom/crx#41

**Comment by tchap** [comment]
Ok, will close this one...

**Comment by oncletom** [comment]
:smiley:
