### ISSUE TITLE
Npm not picking up 1.x versions by default

### ISSUE THREAD

**Issue by erquhart** [oncletom/grunt-crx#54]
![download 5](https://cloud.githubusercontent.com/assets/2112202/7497146/b32abe3e-f3e6-11e4-9f03-4fa3c3dcc5e0.png)

**Comment by Redsandro** [comment]
The `1.0` versions are published but somehow hidden? Interesting.

**Comment by oncletom** [comment]
Yes, sorry about that, this is due to #44 – I kind of need your help on it :-)

I keep this issue opened to help people find a reason why this is happening.
