### ISSUE TITLE
Please update npm repository

### ISSUE THREAD

**Issue by Redsandro** [oncletom/grunt-crx#58]
Latest version on `npm install` is `0.3.4`. There have been improvements since. :+1: 
Can we get the current version on the npm repo?

**Comment by Redsandro** [comment]
I noticed this issue:
https://github.com/oncletom/grunt-crx/issues/54

Does that mean it is available from `npm`, you just need to pin the version?

**Comment by oncletom** [comment]
Yes exactly, this is done on purpose.

You can type the following to view the 'dist-tags' field of the package:

```bash
$ npm view grunt-crx dist-tags
{ latest: '0.3.4', beta: '1.0.3' }
```

By default npm gets the `default` version and you can install a different branch by `npm install grunt-crx@beta`.

**Comment by oncletom** [comment]
Also please note this is due to #44 and as I lack a bit of time, feel free to contribute the missing fix in order to clear this problem :-)
