### ISSUE TITLE
Package (npm) is out of date

### ISSUE THREAD

**Issue by alanPriceWandCorp** [oncletom/grunt-crx#61]
The package in npm is out of date and doesn't include several fixes.

**Comment by oncletom** [comment]
Thanks @alanPriceWandCorp for the report. Can you be more precise of what makes you thinking it is out of date?

Each git tag matches a correspondant npm version (via `npm view grunt-crx versions`).

Unless you mean master contains feature and fixes which have not been published on npm yet?

Let us know :-)

**Comment by alanPriceWandCorp** [comment]
I guess maybe I was mistaken, but on the [npm site](https://www.npmjs.com/package/grunt-crx) it says the most current version is 0.3.4.  Also, when I did an npm install it also installed version 0.3.4.  According to the `npm view grunt-crx versions` it shows more current releases.   

To fix, I specified the most current version (as of this comment) `1.0.3` and ran an `npm install.` This did fix the issue and brought me up to the latest version.   I don't know if there is a way to tell npm to serve the most recent by default because that would have helped in this situation.  

You can close the issue, it was an issue what npm was serving not with the package being out of date.  

Thanks for a useful tool!

**Comment by oncletom** [comment]
This is mainly due to #44 – which could be easily fixable by using `node-glob` to ignore patterns of files in `crx` directly.

**Comment by alanPriceWandCorp** [comment]
Ah, that makes sense.  I will continue using 1.0.3 since I don't need to ignore files.  Thanks for the heads up!

It would probably be helpful if you specified that at the top of the readme, it might reduce some of the issues that have been logged eg. #45, which I also ran into.   Maybe just a "`Note: v0.3.4 has been tagged as the latest version to avoid security issues in packaged extensions.  See issue #44`." 

Thanks,

**Comment by oncletom** [comment]
@alanPriceWandCorp good idea! Please propose a PR and I'll be happy to merge it :-)
