### ISSUE TITLE
How to upload an extension to the web store?

### ISSUE THREAD

**Issue by arieljannai** [oncletom/grunt-crx#66]
I see that in the [README](../blob/master/README.md/) it's written about the public option, but I couldn't found any other reference in the readme nor the code for such thing.

Does it exist?
If so, how it's being used?

Thanks

**Comment by fcfort** [comment]
@arieljannai This tool can create zip files that can be used to upload to the Chrome web store, but it itself does not upload to the chrome web store, it just creates the zip file for you. See https://github.com/c301/grunt-webstore-upload for something that is capable of submitting packages to the web store.

**Comment by arieljannai** [comment]
Somehow I understood it can also upload to the webstore :sweat_smile: 

Eventually I forked [c301's project](https://github.com/c301/grunt-webstore-upload) so I could use it as a node module.

Here's my project: [webstore-upload](https://github.com/arieljannai/webstore-upload) :grin:
