### ISSUE TITLE
Issues generating .crx file

### ISSUE THREAD

**Issue by botzill** [oncletom/grunt-crx#67]
Hi.

I'm trying ti generate new .crx file with this simple config:

<pre>
crx: {
      dist: {
        "src": [
          "dist/**/*",
          "!.{git,svn}",
          "!*.pem"
        ],
        "dest": "crx/test.crx"
      }
    }
</pre>

And I get this error:

`Warning: Unable to read "dist/_locales/manifest.json" file (Error code: ENOENT). Used --force, continuing.`

Why does it look for `manifest.json` in that dir? 

Thx.

**Comment by fcfort** [comment]
I had the same issue, I was only able to resolve this by upgrading to 1.0.3.

**Comment by botzill** [comment]
@fcfort Thx for response. Can you, please, tell us what exactly did you upgrade to version 1.0.3? Thx.

**Comment by fcfort** [comment]
`npm --save-dev install grunt-crx@1.0.3`

See https://docs.npmjs.com/cli/install

**Comment by botzill** [comment]
Thx @fcfort for useful info. :+1:

**Comment by richburdon** [comment]
Thanks @fcfort; I have 1.0.3, but weirdly npm thinks the latest rev is 0.3.4

$ npm outdated
Package    Current  Wanted  Latest  Location
grunt-crx    1.0.3   1.0.3   0.3.4  

That's also reflected here (Current = 1.0.3; Latest = 0.3.4)
https://www.versioneye.com/nodejs/grunt-crx/1.0.3

So 1.0.3 works, but I keep getting npm warnings.

Make any sense?

**Comment by fcfort** [comment]
Hi @richburdon, the reason for this is issue #44. It appears the author is reluctant to bump up the version in npm without resolving that issue.
